-- データベースの種類: PostgreSQL

-- データベースの作成
CREATE DATABASE todo_app;

-- テーブルの作成
CREATE TABLE todo_app (
    id SERIAL PRIMARY KEY,
    title VARCHAR(30) NOT NULL,
    description VARCHAR(1000),
    partner VARCHAR(30),
    due_date DATE,
    status BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- データの追加
INSERT INTO todo_app (title, description, partner, due_date, status, created_at) VALUES
('新製品の市場調査', '新製品の市場調査を実施し、ターゲット市場のニーズを分析する必要があります。', '株式会社マーケティングソリューション', CURRENT_DATE + INTERVAL '1 day', FALSE, CURRENT_DATE + INTERVAL '2 days'),
('年次報告書の作成', '年度末に向けた年次報告書を作成し、経営陣に提出する予定です。', '有限会社財務サポート', CURRENT_DATE + INTERVAL '15 days', FALSE, CURRENT_DATE + INTERVAL '5 days'),
('営業チームのミーティング', '営業チームとの月次ミーティングを開催し、進捗を確認する必要があります。', '株式会社セールスパートナー', CURRENT_DATE + INTERVAL '10 days', FALSE, CURRENT_DATE + INTERVAL '3 days'),
('顧客対応方針の見直し', '顧客対応方法を見直し、より効率的なプロセスを導入する案を考える必要があります。', '株式会社カスタマーサポート', CURRENT_DATE + INTERVAL '-5 days', FALSE, CURRENT_DATE + INTERVAL '-2 days'),
('新規プロジェクトの立ち上げ', '新しいプロジェクトを立ち上げ、プロジェクトマネージャーとスケジュール調整を行います。', '有限会社イノベーション', CURRENT_DATE + INTERVAL '25 days', FALSE, CURRENT_DATE + INTERVAL '10 days'),
('システム更新計画の策定', '次期システム更新計画を策定し、開発チームとリソース配分を確認する必要があります。', '株式会社テクノロジー開発', CURRENT_DATE + INTERVAL '-10 days', FALSE, CURRENT_DATE + INTERVAL '-3 days'),
('顧客アンケート結果の集計', '顧客アンケートの結果を集計し、次回のキャンペーンに活かせるポイントを抽出します。', '株式会社マーケティングソリューション', CURRENT_DATE + INTERVAL '20 days', FALSE, CURRENT_DATE + INTERVAL '8 days'),
('営業報告書の作成', '営業チームからの月次報告書をまとめ、経営陣に提出する準備をします。', '有限会社セールスサポート', CURRENT_DATE + INTERVAL '30 days', FALSE, CURRENT_DATE + INTERVAL '5 days'),
('ビジネスプランの再評価', 'ビジネスプランの方向性を再評価し、修正案を経営陣に提案する必要があります。', '株式会社戦略パートナー', CURRENT_DATE + INTERVAL '-2 days', FALSE, CURRENT_DATE + INTERVAL '3 days'),
('新規契約の交渉', '新規契約の条件について、パートナーと交渉を行うための資料を準備する必要があります。', '株式会社ビジネスコネクション', CURRENT_DATE + INTERVAL '10 days', FALSE, CURRENT_DATE + INTERVAL '7 days'),
('リーダーシップ研修の実施', '新たなリーダーシップ研修を開催し、チームビルディングを強化する必要があります。', '有限会社人材育成', CURRENT_DATE + INTERVAL '5 days', FALSE, CURRENT_DATE + INTERVAL '2 days'),
('業務改善提案の作成', '業務効率化のための改善提案書を作成し、上司に報告する準備を整える。', '株式会社改善エキスパート', CURRENT_DATE + INTERVAL '18 days', FALSE, CURRENT_DATE + INTERVAL '3 days'),
('顧客契約書の見直し', '顧客との契約内容を見直し、必要な修正点を整理する必要があります。', '株式会社リスクマネジメント', CURRENT_DATE + INTERVAL '8 days', FALSE, CURRENT_DATE + INTERVAL '6 days'),
('月次予算の策定', '月次予算を策定し、各部署との調整を行います。', '有限会社財務分析', CURRENT_DATE + INTERVAL '22 days', FALSE, CURRENT_DATE + INTERVAL '7 days'),
('社内セキュリティ対策の強化', '社内のセキュリティ体制を強化し、最新の脅威に対する対策を講じます。', '株式会社サイバーセキュリティ', CURRENT_DATE + INTERVAL '-3 days', FALSE, CURRENT_DATE + INTERVAL '4 days'),
('新サービスの企画', '新しいサービスを企画し、具体的な実施案を作成する必要があります。', '有限会社サービス開発', CURRENT_DATE + INTERVAL '17 days', FALSE, CURRENT_DATE + INTERVAL '6 days'),
('製品の品質管理', '製品の品質チェックを強化し、不具合がないかを確認する必要があります。', '株式会社品質管理ソリューション', CURRENT_DATE + INTERVAL '12 days', FALSE, CURRENT_DATE + INTERVAL '10 days'),
('売上データの分析', '売上データを分析し、改善点を見つけ出す必要があります。', '株式会社データ解析', CURRENT_DATE + INTERVAL '13 days', FALSE, CURRENT_DATE + INTERVAL '8 days'),
('社内イベントの企画', '社員向けの社内イベントを企画し、開催のための準備を整えます。', '株式会社イベントマネジメント', CURRENT_DATE + INTERVAL '25 days', FALSE, CURRENT_DATE + INTERVAL '4 days'),
('取引先との会議', '取引先との定期会議を開催し、次回の契約条件を確認する。', '株式会社ビジネスコンサルティング', CURRENT_DATE + INTERVAL '3 days', FALSE, CURRENT_DATE + INTERVAL '2 days'),
('企業のSNS運営', '企業SNSの運営を見直し、今後の方針を策定します。', '有限会社メディア戦略', CURRENT_DATE + INTERVAL '5 days', FALSE, CURRENT_DATE + INTERVAL '9 days'),
('製品デザインの最終確認', '製品デザインが完成し、最終確認を行う。', '株式会社デザインスタジオ', CURRENT_DATE + INTERVAL '-8 days', FALSE, CURRENT_DATE + INTERVAL '-1 days'),
('市場調査結果の報告', '市場調査の結果を報告し、次の戦略を決定する必要があります。', '株式会社リサーチパートナー', CURRENT_DATE + INTERVAL '20 days', FALSE, CURRENT_DATE + INTERVAL '10 days'),
('顧客満足度の向上施策', '顧客満足度を向上させるための施策を考え、実行計画を立てる。', '有限会社顧客支援', CURRENT_DATE + INTERVAL '17 days', FALSE, CURRENT_DATE + INTERVAL '6 days'),
('製品在庫の確認', '製品の在庫を確認し、足りない商品を発注する準備をします。', '株式会社流通管理', CURRENT_DATE + INTERVAL '18 days', FALSE, CURRENT_DATE + INTERVAL '9 days'),
('人事評価の実施', '従業員の人事評価を実施し、評価基準を見直す必要があります。', '株式会社人事サポート', CURRENT_DATE + INTERVAL '7 days', FALSE, CURRENT_DATE + INTERVAL '6 days'),
('新規広告キャンペーンの立案', '新しい広告キャンペーンを立案し、効果的な媒体選定を行います。', '有限会社広告企画', CURRENT_DATE + INTERVAL '12 days', FALSE, CURRENT_DATE + INTERVAL '10 days'),
('顧客データの整理', '顧客データを整理し、次回のマーケティングに活かせる情報を抽出します。', '株式会社データ管理', CURRENT_DATE + INTERVAL '22 days', FALSE, CURRENT_DATE + INTERVAL '5 days'),
('財務報告の提出', '月次財務報告を提出する準備を進め、経理部門と最終調整を行います。', '有限会社財務アドバイザー', CURRENT_DATE + INTERVAL '30 days', FALSE, CURRENT_DATE + INTERVAL '8 days'),
('会議資料の準備', '次回の会議で使用する資料を準備し、チームメンバーと内容を確認する。', '株式会社ドキュメント作成', CURRENT_DATE + INTERVAL '15 days', FALSE, CURRENT_DATE + INTERVAL '7 days'),
('新規クライアントの獲得', '新規クライアント獲得に向けて営業資料を準備し、アプローチを行います。', '株式会社セールスネット', CURRENT_DATE + INTERVAL '14 days', FALSE, CURRENT_DATE + INTERVAL '4 days'),
('オンライン研修の実施', 'オンライン研修を実施し、スタッフのスキルアップを図ります。', '有限会社研修プランナー', CURRENT_DATE + INTERVAL '2 days', FALSE, CURRENT_DATE + INTERVAL '6 days'),
('競合分析の実施', '競合他社の分析を行い、自社の優位性をアピールするための資料を作成します。', '株式会社市場分析', CURRENT_DATE + INTERVAL '28 days', FALSE, CURRENT_DATE + INTERVAL '12 days'),
('新製品の販売戦略', '新製品の販売戦略を立て、販売チャネルの最適化を行います。', '株式会社製品戦略', CURRENT_DATE + INTERVAL '5 days', FALSE, CURRENT_DATE + INTERVAL '3 days'),
('税務調査対応', '税務調査に備えて必要書類の準備と関係者との調整を行う。', '有限会社税務アドバイザー', CURRENT_DATE + INTERVAL '12 days', FALSE, CURRENT_DATE + INTERVAL '10 days'),
('新規採用活動', '新規採用活動を行い、面接の日程調整を進める。', '株式会社人材戦略', CURRENT_DATE + INTERVAL '4 days', FALSE, CURRENT_DATE + INTERVAL '3 days'),
('社内システムの監査', '社内システムの監査を行い、セキュリティ面の強化を図る。', '株式会社ITセキュリティ', CURRENT_DATE + INTERVAL '30 days', FALSE, CURRENT_DATE + INTERVAL '11 days'),
('営業目標の達成', '営業目標の達成に向けて、進捗状況を確認し、追加施策を立案します。', '株式会社営業サポート', CURRENT_DATE + INTERVAL '22 days', FALSE, CURRENT_DATE + INTERVAL '4 days'),
('プロジェクトの進捗確認', '進行中のプロジェクトの進捗を確認し、次のステップを決定します。', '有限会社プロジェクトマネジメント', CURRENT_DATE + INTERVAL '18 days', FALSE, CURRENT_DATE + INTERVAL '9 days'),
('製品の配送手配', '新製品の配送手配を行い、納期通りに商品をお届けする準備を整えます。', '株式会社配送サービス', CURRENT_DATE + INTERVAL '20 days', FALSE, CURRENT_DATE + INTERVAL '8 days'),
('取引先との契約更新', '取引先との契約更新に向けて、条件を再調整し最終確認を行います。', '有限会社契約アドバイザー', CURRENT_DATE + INTERVAL '25 days', FALSE, CURRENT_DATE + INTERVAL '10 days'),
('サービスマニュアルの作成', '新しいサービスに関するマニュアルを作成し、スタッフに配布する準備をします。', '株式会社マニュアル制作', CURRENT_DATE + INTERVAL '19 days', FALSE, CURRENT_DATE + INTERVAL '5 days'),
('プロジェクト進行状況の報告', 'プロジェクトの進行状況を報告し、遅延がないか確認する。', '株式会社テクノサポート', CURRENT_DATE + INTERVAL '12 days', FALSE, CURRENT_DATE + INTERVAL '10 days'),
('営業計画の見直し', '営業計画を見直し、次の四半期に向けた修正案を作成する。', '有限会社セールスプランニング', CURRENT_DATE + INTERVAL '-3 days', FALSE, CURRENT_DATE + INTERVAL '5 days'),
('新規顧客獲得キャンペーン', '新規顧客獲得に向けたキャンペーンを実施する。ターゲット層の選定を行う。', '株式会社マーケティングソリューション', CURRENT_DATE + INTERVAL '22 days', FALSE, CURRENT_DATE + INTERVAL '15 days'),
('新規プロジェクトの立ち上げ', '新規プロジェクトを立ち上げ、メンバーと役割分担を行う。', '有限会社プロジェクト管理', CURRENT_DATE + INTERVAL '5 days', FALSE, CURRENT_DATE + INTERVAL '8 days'),
('月次売上報告書作成', '月次売上報告書を作成し、上層部に提出する準備をする。', '株式会社営業支援', CURRENT_DATE + INTERVAL '18 days', FALSE, CURRENT_DATE + INTERVAL '10 days'),
('社内システム改善提案', '現在の社内システムに関する改善提案を行う。', '株式会社ITソリューション', CURRENT_DATE + INTERVAL '20 days', FALSE, CURRENT_DATE + INTERVAL '8 days'),
('顧客満足度向上施策', '顧客満足度向上のための施策を考え、実行計画を立てる。', '有限会社カスタマーサービス', CURRENT_DATE + INTERVAL '25 days', FALSE, CURRENT_DATE + INTERVAL '5 days'),
('プロダクトの仕様確認', 'プロダクトの仕様を最終確認し、開発チームに共有する。', '株式会社製品開発', CURRENT_DATE + INTERVAL '10 days', FALSE, CURRENT_DATE + INTERVAL '7 days'),
('営業戦略の見直し', '営業戦略を見直し、新たなターゲット市場を設定する。', '有限会社営業戦略室', CURRENT_DATE + INTERVAL '8 days', FALSE, CURRENT_DATE + INTERVAL '6 days'),
('年度末決算の準備', '年度末決算に向けて、必要な資料を準備する。', '株式会社会計サポート', CURRENT_DATE + INTERVAL '3 days', FALSE, CURRENT_DATE + INTERVAL '1 days'),
('取引先との契約更新', '取引先との契約更新に関して調整を行う。', '株式会社ビジネスアドバイザー', CURRENT_DATE + INTERVAL '17 days', FALSE, CURRENT_DATE + INTERVAL '14 days'),
('新しいプロジェクト計画', '新しいプロジェクトの計画を策定し、進行スケジュールを決定する。', '有限会社開発マネジメント', CURRENT_DATE + INTERVAL '10 days', FALSE, CURRENT_DATE + INTERVAL '4 days'),
('年次報告書の作成', '年次報告書を作成し、全体の業績を振り返る。', '株式会社経営支援', CURRENT_DATE + INTERVAL '30 days', FALSE, CURRENT_DATE + INTERVAL '17 days'),
('商品在庫の確認', '商品の在庫を確認し、欠品がないかチェックする。', '株式会社物流サポート', CURRENT_DATE + INTERVAL '14 days', FALSE, CURRENT_DATE + INTERVAL '12 days'),
('新製品発表会の準備', '新製品発表会に向けて準備を進め、会場の手配をする。', '株式会社プロモーションサポート', CURRENT_DATE + INTERVAL '12 days', FALSE, CURRENT_DATE + INTERVAL '5 days'),
('営業データの分析', '営業データを分析し、次回の営業戦略に活かすためのインサイトを抽出する。', '有限会社営業分析', CURRENT_DATE + INTERVAL '15 days', FALSE, CURRENT_DATE + INTERVAL '10 days'),
('社内研修の実施', '社内研修を実施し、社員のスキル向上を図る。', '株式会社人材育成', CURRENT_DATE + INTERVAL '20 days', FALSE, CURRENT_DATE + INTERVAL '18 days'),
('ウェブサイトの更新', '企業のウェブサイトを更新し、最新情報を反映させる。', '有限会社ウェブサービス', CURRENT_DATE + INTERVAL '5 days', FALSE, CURRENT_DATE + INTERVAL '3 days'),
('顧客向けセミナーの準備', '顧客向けのセミナーを準備し、講師と内容を確認する。', '株式会社セミナー運営', CURRENT_DATE + INTERVAL '18 days', FALSE, CURRENT_DATE + INTERVAL '16 days'),
('オンライン広告キャンペーン', 'オンライン広告キャンペーンを開始し、ターゲットを絞って効果を測定する。', '有限会社広告戦略', CURRENT_DATE + INTERVAL '22 days', FALSE, CURRENT_DATE + INTERVAL '12 days'),
('税務申告書の作成', '税務申告書を作成し、税務署に提出する準備を整える。', '株式会社税務サポート', CURRENT_DATE + INTERVAL '28 days', FALSE, CURRENT_DATE + INTERVAL '14 days'),
('社員のパフォーマンス評価', '社員のパフォーマンス評価を行い、評価結果をフィードバックする。', '有限会社人事管理', CURRENT_DATE + INTERVAL '8 days', FALSE, CURRENT_DATE + INTERVAL '7 days'),
('顧客対応改善策の実施', '顧客対応に関する改善策を実施し、対応品質を向上させる。', '株式会社カスタマーケア', CURRENT_DATE + INTERVAL '25 days', FALSE, CURRENT_DATE + INTERVAL '15 days'),
('取引先の新規開拓', '取引先の新規開拓を行い、次の契約に向けてアプローチを行う。', '有限会社ビジネスデベロップメント', CURRENT_DATE + INTERVAL '18 days', FALSE, CURRENT_DATE + INTERVAL '12 days'),
('新サービスのリリース', '新しいサービスをリリースし、マーケティング活動を開始する。', '株式会社サービス開発', CURRENT_DATE + INTERVAL '13 days', FALSE, CURRENT_DATE + INTERVAL '6 days'),
('サプライチェーンの最適化', 'サプライチェーンの最適化を進め、コスト削減を図る。', '株式会社サプライチェーンマネジメント', CURRENT_DATE + INTERVAL '17 days', FALSE, CURRENT_DATE + INTERVAL '10 days'),
('新規法人設立準備', '新規法人設立に向けて準備を進め、必要な書類を整える。', '有限会社ビジネスサポート', CURRENT_DATE + INTERVAL '23 days', FALSE, CURRENT_DATE + INTERVAL '19 days'),
('経営戦略の再評価', '経営戦略を再評価し、今後の方針を決定する。', '株式会社経営サポート', CURRENT_DATE + INTERVAL '2 days', FALSE, CURRENT_DATE + INTERVAL '4 days'),
('市場調査レポートの作成', '市場調査を行い、その結果をレポートとしてまとめる。', '有限会社マーケットリサーチ', CURRENT_DATE + INTERVAL '30 days', FALSE, CURRENT_DATE + INTERVAL '17 days'),
('顧客からのフィードバック収集', '顧客からのフィードバックを収集し、改善案を立てる。', '株式会社カスタマーリレーション', CURRENT_DATE + INTERVAL '11 days', FALSE, CURRENT_DATE + INTERVAL '6 days'),
('パートナーシップ契約の見直し', 'パートナーシップ契約を見直し、新しい条件を提案する。', '有限会社パートナーシップ', CURRENT_DATE + INTERVAL '26 days', FALSE, CURRENT_DATE + INTERVAL '14 days'),
('オンラインストアの運営強化', 'オンラインストアの運営を強化し、集客を増加させるための施策を講じる。', '株式会社ネットショップ運営', CURRENT_DATE + INTERVAL '9 days', FALSE, CURRENT_DATE + INTERVAL '5 days'),
('税務監査の準備', '税務監査に向けて、必要な書類やデータを整える。', '株式会社監査サポート', CURRENT_DATE + INTERVAL '3 days', FALSE, CURRENT_DATE + INTERVAL '2 days'),
('商品マーケティング戦略の策定', '商品のマーケティング戦略を策定し、プロモーション活動を計画する。', '有限会社プロモーション戦略', CURRENT_DATE + INTERVAL '16 days', FALSE, CURRENT_DATE + INTERVAL '12 days'),
('事業計画書の見直し', '事業計画書を見直し、新しい目標を設定する。', '株式会社ビジネスプランニング', CURRENT_DATE + INTERVAL '28 days', FALSE, CURRENT_DATE + INTERVAL '18 days'),
('新製品の販売戦略立案', '新製品の販売戦略を立案し、マーケティング活動を強化する。', '株式会社販売戦略', CURRENT_DATE + INTERVAL '4 days', FALSE, CURRENT_DATE + INTERVAL '6 days'),
('社員の福利厚生見直し', '社員の福利厚生を見直し、より良い環境を提供するための提案を行う。', '有限会社人事労務', CURRENT_DATE + INTERVAL '14 days', FALSE, CURRENT_DATE + INTERVAL '7 days'),
('コスト削減施策の提案', 'コスト削減施策を提案し、各部署と調整を行う。', '株式会社コストマネジメント', CURRENT_DATE + INTERVAL '30 days', FALSE, CURRENT_DATE + INTERVAL '17 days'),
('次期予算案の策定', '次期予算案を策定し、経理部門と調整を行う。', '有限会社財務戦略', CURRENT_DATE + INTERVAL '18 days', FALSE, CURRENT_DATE + INTERVAL '15 days'),
('人材採用計画の立案', '人材採用計画を立案し、募集要項を作成する。', '株式会社人事サポート', CURRENT_DATE + INTERVAL '24 days', FALSE, CURRENT_DATE + INTERVAL '18 days'),
('新規事業開発の計画', '新規事業開発に向けた計画を立案し、資金調達を検討する。', '有限会社事業開発', CURRENT_DATE + INTERVAL '10 days', FALSE, CURRENT_DATE + INTERVAL '3 days'),
('顧客からのクレーム対応', '顧客からのクレームに対応し、問題解決に向けた手続きを進める。', '株式会社クレーム対応', CURRENT_DATE + INTERVAL '5 days', FALSE, CURRENT_DATE + INTERVAL '2 days'),
('新規プロモーション案の作成', '新規プロモーション案を作成し、各部署と協力して進める。', '有限会社プロモーションチーム', CURRENT_DATE + INTERVAL '15 days', FALSE, CURRENT_DATE + INTERVAL '12 days'),
('新規プロジェクトの立ち上げ', '新しいプロジェクトを立ち上げるための準備を進め、チームメンバーを選定する。', '株式会社テクノイノベーション', CURRENT_DATE + INTERVAL '14 days', FALSE, CURRENT_DATE + INTERVAL '10 days'),
('営業会議の準備', '営業会議を開き、先月の業績を分析して今後の営業戦略を話し合う。', '有限会社セールスアドバイザー', CURRENT_DATE + INTERVAL '8 days', FALSE, CURRENT_DATE + INTERVAL '5 days'),
('市場調査の結果分析', '実施した市場調査の結果をまとめ、ビジネス戦略に反映させる。', '株式会社マーケットリサーチ', CURRENT_DATE + INTERVAL '20 days', FALSE, CURRENT_DATE + INTERVAL '15 days'),
('広告キャンペーンの計画', '次の広告キャンペーンを計画し、ターゲット層と広告手法を決定する。', '株式会社広告プロモーション', CURRENT_DATE + INTERVAL '25 days', FALSE, CURRENT_DATE + INTERVAL '18 days'),
('新製品の発売計画', '新製品の発売に向けたスケジュールを策定し、販促活動を進める。', '有限会社製品開発センター', CURRENT_DATE + INTERVAL '12 days', FALSE, CURRENT_DATE + INTERVAL '6 days'),
('次期営業戦略の立案', '次期営業戦略を立案し、担当者に指示を出す。', '株式会社営業支援', CURRENT_DATE + INTERVAL '22 days', FALSE, CURRENT_DATE + INTERVAL '18 days'),
('顧客満足度調査の実施', '顧客満足度調査を実施し、改善点を抽出する。', '有限会社カスタマーケア', CURRENT_DATE + INTERVAL '18 days', FALSE, CURRENT_DATE + INTERVAL '10 days'),
('社内ITシステムの改善', '社内ITシステムの不具合を修正し、業務効率を向上させる。', '株式会社ITソリューション', CURRENT_DATE + INTERVAL '30 days', FALSE, CURRENT_DATE + INTERVAL '25 days'),
('経営戦略の見直し', '経営戦略を見直し、現状の課題を洗い出す。', '有限会社経営サポート', CURRENT_DATE + INTERVAL '5 days', FALSE, CURRENT_DATE + INTERVAL '3 days'),
('人材採用計画の立案', '人材採用の計画を立て、募集要項を作成する。', '株式会社人材リクルート', CURRENT_DATE + INTERVAL '10 days', FALSE, CURRENT_DATE + INTERVAL '7 days'),
('契約更新の交渉', '取引先との契約更新に向けた交渉を開始する。', '株式会社ビジネスサポート', CURRENT_DATE + INTERVAL '15 days', FALSE, CURRENT_DATE + INTERVAL '12 days'),
('社内研修の実施', '社員向けの社内研修を実施し、スキルアップを図る。', '有限会社研修運営', CURRENT_DATE + INTERVAL '20 days', FALSE, CURRENT_DATE + INTERVAL '14 days'),
('次期予算案の策定', '次期予算案を策定し、各部門と調整を行う。', '株式会社財務戦略', CURRENT_DATE + INTERVAL '7 days', FALSE, CURRENT_DATE + INTERVAL '5 days'),
('年次報告書の作成', '年次報告書を作成し、業績を社内外に報告する。', '株式会社経営企画', CURRENT_DATE + INTERVAL '27 days', FALSE, CURRENT_DATE + INTERVAL '20 days'),
('新規取引先との会議', '新規取引先との初回会議を設定し、ビジネスの方向性を確認する。', '有限会社取引先開拓', CURRENT_DATE + INTERVAL '3 days', FALSE, CURRENT_DATE + INTERVAL '2 days'),
('マーケティング戦略の見直し', 'マーケティング戦略を見直し、効果的な施策を提案する。', '株式会社マーケティングプラン', CURRENT_DATE + INTERVAL '17 days', FALSE, CURRENT_DATE + INTERVAL '11 days'),
('在庫管理の改善', '在庫管理システムを改善し、効率的な運営を目指す。', '有限会社物流管理', CURRENT_DATE + INTERVAL '21 days', FALSE, CURRENT_DATE + INTERVAL '14 days'),
('サービス品質の向上', 'サービス品質の向上に向けた取り組みを強化する。', '株式会社品質向上', CURRENT_DATE + INTERVAL '11 days', FALSE, CURRENT_DATE + INTERVAL '6 days'),
('次期製品の設計', '次期製品の設計案を決定し、開発チームに指示を出す。', '有限会社製品設計', CURRENT_DATE + INTERVAL '9 days', FALSE, CURRENT_DATE + INTERVAL '7 days'),
('グローバル展開の準備', '海外市場への展開に向けた準備を進める。', '株式会社国際戦略', CURRENT_DATE + INTERVAL '13 days', FALSE, CURRENT_DATE + INTERVAL '10 days'),
('経費削減施策の提案', '経費削減に向けた施策を各部門に提案し、実行計画を策定する。', '有限会社経費削減サポート', CURRENT_DATE + INTERVAL '5 days', FALSE, CURRENT_DATE + INTERVAL '4 days'),
('イベントの運営準備', '次のイベントを運営するための準備を行う。', '株式会社イベント企画', CURRENT_DATE + INTERVAL '25 days', FALSE, CURRENT_DATE + INTERVAL '18 days'),
('企業向けセミナーの準備', '企業向けのセミナーを準備し、講師や内容を決定する。', '有限会社セミナー運営', CURRENT_DATE + INTERVAL '8 days', FALSE, CURRENT_DATE + INTERVAL '6 days'),
('企業研修の内容見直し', '企業研修の内容を見直し、現状に合った内容に変更する。', '株式会社人材育成', CURRENT_DATE + INTERVAL '19 days', FALSE, CURRENT_DATE + INTERVAL '15 days'),
('製品の品質チェック', '製品の品質チェックを行い、問題がないか確認する。', '有限会社品質管理', CURRENT_DATE + INTERVAL '16 days', FALSE, CURRENT_DATE + INTERVAL '10 days'),
('従業員の評価制度改定', '従業員評価制度を改定し、より公正で透明性の高い制度を導入する。', '株式会社人事戦略', CURRENT_DATE + INTERVAL '22 days', FALSE, CURRENT_DATE + INTERVAL '18 days'),
('ウェブサイトの更新', 'ウェブサイトを最新の情報に更新し、ユーザビリティを向上させる。', '有限会社ウェブデザイン', CURRENT_DATE + INTERVAL '30 days', FALSE, CURRENT_DATE + INTERVAL '25 days'),
('新規顧客開拓計画', '新規顧客の開拓計画を立て、ターゲット層の分析を行う。', '株式会社顧客開拓', CURRENT_DATE + INTERVAL '12 days', FALSE, CURRENT_DATE + INTERVAL '7 days'),
('パートナーシップ契約の交渉', '新しいパートナーシップ契約を交渉し、条件を整える。', '有限会社パートナーシップ', CURRENT_DATE + INTERVAL '28 days', FALSE, CURRENT_DATE + INTERVAL '20 days'),
('製品のプロモーション活動', '製品のプロモーション活動を強化し、ブランド認知度を高める。', '株式会社プロモーションサポート', CURRENT_DATE + INTERVAL '10 days', FALSE, CURRENT_DATE + INTERVAL '8 days');

